sonar.projectKey=idiyengineering_atlassian-jira-fields-app
sonar.organization=idiyengineering

# Analyze application code only.
sonar.sources=atlassian-jira-fields-viewer/src
sonar.exclusions=**/test/**,**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=atlassian-jira-fields-viewer/coverage/lcov.info
